.TH ffmpeg-gui 1 "January  8, 2012"
.SH NAME
ffmpeg-gui \- Frontend for ffmpeg
.SH SYNOPSIS
.B ffmpeg-gui
.SH DESCRIPTION
This manual page documents briefly the
.B ffmpeg-gui
program frontend for ffmpeg suite.
.PP
\fBffmpeg-gui\fP is a frontend to ffmpeg that allow you to set most important
conversion parameters. You can choose your preferred installed preset
or make and save your own. You can batch convert multiple videos and have
a log file in html format, if destination size ratio differ, ffmpegGUI
will automatically add a padding.

.SH ISSUES
Some scaling factor are hihacked, and the due this frontend are a command line 
the process of transcoding are suject to the compatibility between codecs itself, 
so some combinations could fail normaly, so just reconfigure the choosen options 
and go encoding again!

.SH AUTHOR
ffmpeg-gui was written by Marco Bavagnoli <lil.deimos@gmail.com> in 2012 and 
then stolen, now its revived for VenenuX.
.PP
This manual page was written by \fBPICCORO Lenz McKAY\fP <alduvi11@gmail.com>,
for the VenenuX project (but may be used by others).
